WIP : Feature/acf page builder templates
studiometa/wordpress-project pull request #4
Opened 2022-09-22 09:01 UTC by Guillaume-meta

Objective
Have some default blocks when we start some simple project. We will just have to skin them.

First Draft
* Create some default blocks
* Begin template creation for these blocks

2022-09-28 09:36 UTC, perruche commented on web/wp-content/themes/studiometa/app/Blocks/Video.php
> +		$video_block->addText( 'title', array( 'label' => 'Titre de la vidéo' ) )
**détails/ajouter traduction** `array( 'label' => __( 'Titre de la vidéo', 'acf' ) ) )`

2022-09-28 09:39 UTC, perruche commented on web/wp-content/themes/studiometa/app/Managers/ACFManager.php
> +			->addLayout(Video::get_block())
who's is better ?
->addLayout(new Video('video2'))
->addLayout(Video::get_block('video2'))

2022-09-28 09:46 UTC, perruche commented on web/wp-content/themes/studiometa/templates/organisms/block_video.twig
> +          <span class="content">
**details** use tw grid to reduce the number of divs

2022-09-28 12:59 UTC, Guillaume-meta commented on web/wp-content/themes/studiometa/app/Managers/ACFManager.php
> +			->addLayout(Video::get_block())
hey @coraliebach too

2022-09-29 11:53 UTC, lusimeon commented on web/wp-content/themes/studiometa/app/Blocks/AbstractBlock.php
> +	public static function get_block( string $name ) {}
**nitpick:** This method must be abstract `abstract public…`

2022-09-29 12:14 UTC, lusimeon commented on web/wp-content/themes/studiometa/app/Managers/ACFManager.php
> +			->addLayout(Video::get_block())
In my opinion first approach is more object oriented and better. The factory pattern isn't needed here because blocks instanciation does not depends on dynamic parameters. We know what we want to create.

A block should looks like this: 
```php
class Video extends FieldsBuilder
{
    public function __construct($name)
   {
        $block = parent::__construct($name);
        $block->addText(…)
              ->addFile();
   }
}

// Use it
$builder_group->addLayout(new Video('my_video'))
```

2022-10-10 08:44 UTC, perruche requested changes
Nice work 👏 
I'll suggest a few minor changes, up to discussion if needed

2022-10-10 08:44 UTC, perruche commented on web/wp-content/themes/studiometa/templates/molecules/video.twig
> +            icon_only: true
**suggestion/accessiblity:** Add attribute aria-label: Play the video

2022-10-10 08:44 UTC, perruche commented on web/wp-content/themes/studiometa/templates/molecules/video.twig
> +            <span class="block mt-3">{{ video_legend }}</span>
**suggestion/accessibility** Add id="video-desc"

2022-10-10 08:44 UTC, perruche commented on web/wp-content/themes/studiometa/templates/molecules/video.twig
> +      <video controls
**suggestion/accessibility**: Add attribute `aria-labelledby="video-desc"`

2022-10-10 08:44 UTC, perruche commented on web/wp-content/themes/studiometa/templates/organisms/blocks/block_video.twig
> +<section class="block-video">
**praise:** good idea to set a custom class, to easily identify each block while inspecting the page, should add to all blocks ?

2022-10-10 08:44 UTC, perruche commented on web/wp-content/themes/studiometa/templates/organisms/blocks/block_wysiwyg.twig
> +<div class="grid grid-cols-12 gap-5">
**suggestion:** Use <section> HTML tag for all parent element of a block ?

2022-10-10 08:44 UTC, perruche commented on web/wp-content/themes/studiometa/app/Blocks/Video.php
> +				'instructions' => 'Caché si non renseigné',
**question:** Should we add translatable string for all the page builder admin texts?

2022-10-10 12:15 UTC, notjb commented on web/wp-content/themes/studiometa/app/Blocks/Accordion.php
> +			->addText( 'theme_title', array( 'label' => 'Titre du chapitre' ) )
**suggestion**
How about making the labels translatable ? 
Could be interesting for i18n purpose :)
`->addText( 
  'theme_title', 
  array( 'label' => __( 'Titre du chapitre' , 'studiometa' ) )
)`

2022-10-10 12:35 UTC, notjb reviewed
"i see what you did there" 👌

2022-10-10 12:35 UTC, notjb commented on web/wp-content/themes/studiometa/app/Blocks/ImageFullWidth.php
> + * Video Block for templating
**nitpick:**
Update comment according to file title 😇

2022-10-26 08:16 UTC, titouanmathis reviewed
Some minor adjustments before merging, but this is great! 👍

2022-10-26 08:16 UTC, titouanmathis commented on web/wp-content/themes/studiometa/app/Blocks/Video.php
> +				'label'        => 'Vidéo',
**nitpick:** Use `__( 'Vidéo', 'studiometa' )` for the label

2022-10-26 08:16 UTC, titouanmathis commented on web/wp-content/themes/studiometa/app/Blocks/Wysiwyg.php
> +class Wysiwyg extends AbstractBlock {
**question:** Shouldn't this block be named `Text` to follow the naming convention of `ImageText`? 🤔 

Maybe it could also be reused in the `ImageText` block?

2022-10-26 08:16 UTC, titouanmathis commented on web/wp-content/themes/studiometa/app/Managers/ACFManager.php
> +		$builder_group->addFlexibleContent( 'builder', array( 'button_label' => 'Ajouter section' ) )
**nitpick:** Use the `__` function for the button's label

2022-10-26 08:16 UTC, titouanmathis commented on web/wp-content/themes/studiometa/src/css/admin/editor-style.scss
> +  h1 {
I think a `_wysiwyg.scss` atom which could be imported in `app.scss` and `editor-style.scss` would work.

2022-10-26 08:16 UTC, titouanmathis commented on web/wp-content/themes/studiometa/src/css/admin/editor-style.scss
> +  h1 {
Well, it already exists, so we can simply import it here.

2022-10-26 08:16 UTC, titouanmathis commented on web/wp-content/themes/studiometa/templates/organisms/blocks/block_accordion.twig
> +{#
**nitpick:** We should use `kebab-case` style for file names

A simple replace from `_` to `-` when trying to include a file should work.

2022-10-26 14:01 UTC, perruche commented on web/wp-content/themes/studiometa/src/css/admin/editor-style.scss
> +  h1 {
the rules in `app` and `editor-style` are not from the same ancestor `.wysiwyg h1` vs `#tinymce h1`

2022-10-26 15:06 UTC, titouanmathis approved these changes

2022-12-22 14:45 UTC, closed without merging

2022-12-22 14:47 UTC, titouanmathis commented
This was merged in `develop`.